---
- name: config_logstash | clearing existing logstash config
  file:
    path: "{{ logstash_config_dir }}"
    state: absent
  when: clear_logstash_config is defined and clear_logstash_config

- name: config_logstash | recreating logstash config directory if previously cleared
  file:
    path: "{{ logstash_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  when: clear_logstash_config is defined and clear_logstash_config

- name: config_logstash | removing original logstash config if it exists
  file:
    path: "{{ logstash_config_dir }}/logstash.conf"
    state: absent
  notify: restart logstash

- name: config_logstash | configuring logstash
  template:
    src: "etc/logstash/conf.d/{{ item }}.conf.j2"
    dest: "{{ logstash_config_dir }}/{{ item }}.conf"
    owner: logstash
    group: logstash
    mode: 0644
    validate: "/opt/logstash/bin/logstash -tf %s"
  notify: restart logstash
  with_items: logstash_base_configs

- name: config_logstash | creating logstash pattern folders
  file:
    path: "{{ item }}"
    state: directory
    owner: logstash
    group: logstash
    mode: 0775
    recurse: yes
  with_items:
    - /opt/logstash/lib/logstash/outputs/elasticsearch
    - /opt/logstash/patterns
