---
- name: validate_permissions | validating permissions on logstash folder
  file:
    path: "{{ logstash_folder }}"
    state: "directory"
    recurse: yes
    owner: "logstash"
    group: "logstash"
  notify: "restart logstash"
