---
- hosts: all
  sudo: true
  remote_user: vagrant
  vars:
    - deb_db_password: $6$3BFlAptb$S4313dXRWU12lLTXbh2/h3mBOdUWA1pQMQ7uYwWVT32Ko.R.cRdIZETFHKbgdpWRNbRe6XoKECIEFxqgFu2vp.
    - enable_pdns_web_server: true
    - install_dhcp: false  #defines if dhcp services should be installed
    - install_dns: true  #defines if powerdns (dns) services should be installed
    - install_logstash: false  #defines if logstash should be installed to monitor powerdns
    - install_phpipam: true  #defines if phpipam services should be installed
    - install_quagga: false  #defines if quagga (routing) should be installed for AnyCast services
    - mysql_root_password: $6$3BFlAptb$S4313dXRWU12lLTXbh2/h3mBOdUWA1pQMQ7uYwWVT32Ko.R.cRdIZETFHKbgdpWRNbRe6XoKECIEFxqgFu2vp.
  roles:
    - mrlesmithjr.apache2
    - mrlesmithjr.config-interfaces
    - mrlesmithjr.mariadb-mysql
    - { role: mrlesmithjr.isc-dhcp, when: install_dhcp is defined and install_dhcp }
    - { role: mrlesmithjr.logstash, when: install_logstash is defined and install_logstash }
    - { role: mrlesmithjr.phpipam, when: install_phpipam is defined and install_phpipam }
    - { role: mrlesmithjr.powerdns, when: install_dns is defined and install_dns }
    - { role: mrlesmithjr.quagga, when: (install_quagga is defined and install_quagga) and (enable_pdns_anycast is defined and enable_pdns_anycast) }
