---
- src: https://github.com/mrlesmithjr/ansible-apache2.git
- src: https://github.com/mrlesmithjr/ansible-base.git
- src: https://github.com/mrlesmithjr/ansible-bootstrap.git
- src: https://github.com/mrlesmithjr/ansible-config-interfaces.git
- src: https://github.com/mrlesmithjr/ansible-etc-hosts.git
- src: https://github.com/mrlesmithjr/ansible-isc-dhcp.git
- src: https://github.com/mrlesmithjr/ansible-logstash.git
- src: https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster.git
- src: https://github.com/mrlesmithjr/ansible-mariadb-mysql.git
- src: https://github.com/mrlesmithjr/ansible-ntp.git
- src: https://github.com/mrlesmithjr/ansible-phpipam.git
- src: https://github.com/mrlesmithjr/ansible-powerdns.git
- src: https://github.com/mrlesmithjr/ansible-quagga.git
