---
- name: debian_pdns_server | installing powerdns pre-reqs
  apt:
    name: "{{ item }}"
    state: "present"
    force: "yes"
  with_items:
    - git
    - jq
    - python-mysqldb

- name: debian_pdns_server | downloading powerdns
  get_url:
    url: "{{ pdns_download_url }}/deb/pdns-static_{{ pdns_server_version }}_amd64.deb"
    dest: "/opt/pdns-static_{{ pdns_server_version }}_amd64.deb"
  when: ansible_architecture == "x86_64"

- name: debian_pdns_server | installing powerdns
  apt:
    deb: "/opt/pdns-static_{{ pdns_server_version }}_amd64.deb"
  notify: restart pdns
  when: ansible_architecture == "x86_64"

- name: debian_pdns_server | downloading powerdns
  get_url:
    url: "{{ pdns_download_url }}/deb/pdns-static_{{ pdns_server_version }}_i386.deb"
    dest: "/opt/pdns-static_{{ pdns_server_version }}_i386.deb"
  when: ansible_architecture == "i386"

- name: debian_pdns_server | installing powerdns
  apt:
    deb: "/opt/pdns-static_{{ pdns_server_version }}_i386.deb"
  notify: restart pdns
  when: ansible_architecture == "i386"
