---
# tasks file for ansible-powerdns
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: remove_logstash.yml
  tags:
    - remove_logstash
  when: (install_logstash is defined and not install_logstash) or install_logstash is not defined

#- include: cron.yml
#  tags:
#    - cron
#  when: enable_pdns_anycast is defined and enable_pdns_anycast

- include: pdns_zones.yml
  tags:
    - create_pdns_zones
  when: create_pdns_zones is defined and create_pdns_zones

- include: pdns_records.yml
  tags:
    - create_pdns_records
  when: (create_pdns_records is defined and create_pdns_records) and pdns_records is defined
