---
- include: debian_pdns_recursor.yml
  when: ansible_os_family == "Debian"

- include: redhat_pdns_recursor.yml
  when: ansible_os_family == "RedHat"

- name: pdns_recursor | configuring powerdns recursor
  template:
    src: "etc/powerdns/recursor.conf.j2"
    dest: "/etc/powerdns/recursor.conf"
    owner: "root"
    group: "root"
  notify: restart pdns recursor
  register: "pdns_recursor_configured"

- name: pdns_recursor | ensuring pdns recursor is enabled
  service:
    name: "pdns-recursor"
    enabled: yes

- name: pdns_recursor | restarting powerdns recursor
  service:
    name: "pdns-recursor"
    state: "restarted"
  when: pdns_recursor_configured.changed
