---
- name: redhat_pdns_recursor | downloading powerdns recursor
  get_url:
    url: "{{ pdns_download_url }}/rpm/pdns-recursor-{{ pdns_recursor_version }}.x86_64.rpm"
    dest: "/opt/pdns-recursor-{{ pdns_recursor_version }}.x86_64.rpm"

- name: redhat_pdns_recursor | installing powerdns recursor
  yum:
    name: "/opt/pdns-recursor-{{ pdns_recursor_version }}.x86_64.rpm"
  notify: restart pdns recursor
