---
# handlers file for ansible-logstash
- name: init logstash
  command: update-rc.d logstash defaults 96 04

- name: remove logstash-web
  command: update-rc.d -f logstash-web remove

- name: restart logstash
  service:
    name: logstash
    state: restarted

- name: stop logstash-web
  service:
    name: logstash-web
    state: stopped
