---
# handlers file for ansible-powerdns
- name: restart pdns
  service:
    name: "pdns"
    state: "restarted"
    sleep: 10

- name: restart pdns recursor
  service:
    name: "pdns-recursor"
    state: "restarted"

- name: restart apache2
  service:
    name: "apache2"
    state: "restarted"

- name: restart mysql
  service:
    name: "mysql"
    state: "restarted"
