---
- name: config_quagga | ensuring vlan package is installed
  apt: name=vlan state=present

- name: config_quagga | configuring network settings
  sysctl: name="{{ item.name }}" value="{{ item.value }}" state=present reload=yes
  with_items: sysctl_network_settings
  when: sysctl_network_settings is defined

- name: config_quagga | configuring quagga
  template: src=etc/quagga/{{ item }}.j2 dest={{ quagga_root_dir }}/{{ item }} owner=root group=root mode=0644
  notify: restart quagga
  with_items: quagga_configs
  when: (config_glusterfs is defined and not config_glusterfs) or config_glusterfs is not defined

- name: config_quagga | configuring ospf
  template: src=etc/quagga/ospfd.conf.j2 dest={{ quagga_root_dir }}/ospfd.conf owner=root group=root mode=0644
  notify: restart quagga
  when: ((quagga_enable_ospfd is defined and quagga_enable_ospfd) and (config_glusterfs is defined and not config_glusterfs)) or ((quagga_enable_ospfd is defined and quagga_enable_ospfd) and config_glusterfs is not defined)

- name: config_quagga | configuring bgp
  template: src=etc/quagga/bgpd.conf.j2 dest={{ quagga_root_dir }}/bgpd.conf owner=root group=root mode=0644
  notify: restart quagga
#  with_items: quagga_bgp_router_configs
  when: quagga_bgp_router_configs is not defined and ((quagga_enable_bgpd is defined and quagga_enable_bgpd) and (config_glusterfs is defined and not config_glusterfs)) or ((quagga_enable_bgpd is defined and quagga_enable_bgpd) and config_glusterfs is not defined)

- name: config_quagga | configuring bgp
  template: src=etc/quagga/bgpd.conf.j2 dest={{ quagga_root_dir }}/bgpd.conf owner=root group=root mode=0644
  notify: restart quagga
  with_items: quagga_bgp_router_configs
  when: (quagga_bgp_router_configs is defined and (item.name == inventory_hostname)) and ((quagga_enable_bgpd is defined and quagga_enable_bgpd) and (config_glusterfs is defined and not config_glusterfs)) or ((quagga_enable_bgpd is defined and quagga_enable_bgpd) and config_glusterfs is not defined)

- name: config_quagga | setting permissions on files within /etc/quagga
  file: path=/etc/quagga/ owner=quagga group=quagga mode=0644 state=directory recurse=yes

- name: config_quagga | setting permissions on folder /etc/quagga
  file: path=/etc/quagga owner=quagga group=quaggavty mode=0775 state=directory
