---
- name: debian | installing quagga pre-reqs
  apt: name={{ item }} state=present
  with_items:
    - lldpd
    - vlan

- name: debian | installing quagga
  apt: name=quagga state=present

- name: debian | enabling quagga
  service: name=quagga state=started enabled=yes
