---
- name: Set MariaDB root password
  command: "debconf-set-selections <<< 'mysql-server-10.0 mysql-server/root_password password {{ mysql_root_password }}'"
  command: "debconf-set-selections <<< 'mysql-server-10.0 mysql-server/root_password_again password {{ mysql_root_password }}'"
  changed_when: false # Never report as changed
