---
- name: redhat | adding mariadb repo
  template:
    src: "etc/yum.repos.d/MariaDB.repo.j2"
    dest: "/etc/yum.repos.d/MariaDB.repo"
    owner: root
    group: root
  register: repo_added

- name: redhat | installing mariadb mysql
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - MariaDB-server
    - MySQL-python
  when: >
        ansible_distribution != "Fedora"

- name: redhat | installing mariadb mysql
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - MariaDB-server
    - MySQL-python
  when: >
        ansible_distribution == "Fedora"

- name: redhat | ensuring mariadb mysql is enabled on boot and started
  service:
    name: mysql
    state: started
    enabled: yes
