---
# handlers file for ansible-mariadb-galera-cluster
- name: "restart mysql"
  service:
    name: "mysql"
    state: "restarted"

- name: "reload mysql"
  service:
    name: "mysql"
    state: "reloaded"
