---
- name: upgrade | checking if {{ phpipam_root }} exists
  stat:
    path: "{{ phpipam_root }}"
  register: phpipam_root_check

- name: upgrade | moving {{ phpipam_root }} directory to {{ phpipam_root }}.{{ date }}
  command: "mv {{ phpipam_root }} {{ phpipam_root }}.{{ date }}"
  when: phpipam_root_check.stat.exists
