---
- name: debian | setting dns search suffix
  lineinfile:
    dest: /etc/network/interfaces
    regexp: "^dns-search"
    line: "dns-search {{ dns_search }}"
    state: present
  notify: update resolvconf
  when: update_dns_search and pri_interface_method is defined and pri_interface_method == "static"

- name: debian | removing dns search suffix
  lineinfile:
    dest: /etc/network/interfaces
    regexp: "^dns-search"
    line: "dns-search {{ dns_search }}"
    state: absent
  notify: update resolvconf
  when: update_dns_search and pri_interface_method is defined and pri_interface_method == "dhcp"

- name: debian | removing dns search suffix
  lineinfile:
    dest: /etc/network/interfaces
    regexp: "^dns-search"
    line: "dns-search {{ dns_search }}"
    state: absent
  notify: update resolvconf
  when: update_dns_search and pri_interface_method is not defined

- name: debian | removing dns search suffix
  lineinfile:
    dest: /etc/network/interfaces
    regexp: "^dns-search"
    line: "dns-search {{ dns_search }}"
    state: absent
  notify: update resolvconf
  when: not update_dns_search and pri_interface_method is defined and pri_interface_method == "dhcp"
